export const branches = [
  "B.Arch",
  "B.Sc. Computer Science",
  "B.Sc. Multimedia and Animation",
  "B.Sc. (Hons.) Agriculture",
  "B.C.A (Bachelor of Computer Applications)",
  "B.Tech - Aerospace Engineering",
  "B.Tech - Biotechnology",
  "B.Tech - Chemical Engineering",
  "B.Tech - Civil Engineering",
  "B.Tech - Computer Science and Engineering",
  "B.Tech - Computer Science and Engineering (Bioinformatics)",
  "B.Tech - Computer Science & Engineering ( Information Security)",
  "B.Tech - Computer Science and Engineering and Business Systems",
  "B.Tech - Computer Science and Engineering (Data Science)",
  "B.Tech - Computer Science and Engineering (Blockchain)",
  "B.Tech - Computer Science and Engineering (IOT)",
  "B.Tech - Computer Science and Engineering (AI/ML)",
  "B.Tech - Computer Science and Engineering (AI and Data Engineering)",
  "B.Tech - Computer Science and Engineering (Cyber Sec.)",
  "B.Tech - Electrical and Electronics Engineering",
  "B.Tech - Electrical and Computer Science Engineering",
  "B.Tech - Electronics and Communication Engineering",
  "B.Tech - Electronics and Instrumentation Engineering",
  "B.Tech - Electronics and Communication Engineering (Biomedical Engineering)",
  "B.Tech - Electronics Engineering (VLSI Design and Technology)",
  "B.Tech - Health Sciences and Technology",
  "B.Tech - Information Technology",
  "B.Tech - Mechanical Engineering",
  "B.Tech - Mechanical Engineering (Electric Vehicles)",
  "B.Tech - Mechanical Engineering (Smart Manufacturing)",
  "Integrated M.Tech. Software Engineering",
  "Integrated M.Tech. Computer Science and Engineering in collaboration with Virtusa",
  "Integrated M.Tech. Computer Science and Engineering (Data Science)",
  "Integrated M.Sc. Biotechnology (5 Year)",
  "Integrated M.Sc. Food Science and Technology (5 Year)",
  "Integrated M.Sc Computational Statistics and Data Analytics (5 Year)",
  "Integrated M.Sc. Physics (5 Year)",
  "Integrated M.Sc. Chemistry (5 Year)",
  "Integrated M.Sc. Mathematics (5 Year)",
  "M.Tech. Biomedical Engineering",
  "M.Tech. CAD / CAM",
  "M.Tech. Construction Technology and Management",
  "M.Tech. Control and Automation",
  "M.Tech. IoT and Sensor Systems",
  "M.Tech. Mechatronics",
  "M.Tech. Power Electronics and Drives",
  "M.Tech. Structural Engineering",
  "M.Tech. Applied Computational Fluid Dynamics",
  "M.Tech. Automotive Electronics",
  "M.Tech. Automotive Engineering",
  "M.Tech. Biotechnology",
  "M.Tech. Electronics and Communication Engineering (Intelligent Communication Systems)",
  "M.Tech. Manufacturing Engineering",
  "M.Tech. Computer Science and Engineering",
  "M.Tech. Computer Science and Engineering (Artificial Intelligence and Machine Learning)",
  "M.Tech. Computer Science and Engineering (Big Data Analytics)",
  "M.Tech. Computer Science and Engineering (Information Security)",
  "M.Tech. Embedded Systems",
  "M.Tech. VLSI Design",
  "M.Des. (Industrial Design)",
  "M.C.A. (Master of Computer Applications)",
  "M.Sc. Applied MicroBiology",
  "M.Sc. Biomedical Genetics",
  "M.Sc. Biotechnology",
  "M.Sc. Business Statistics",
  "M.Sc. Chemistry",
  "M.Sc. Data Science",
  "M.Sc. Physics",
];

export const schools = [
  "School of Advanced Sciences (SAS)",
  "School of Bio Sciences & Technology (SBST)",
  "School of Civil Engineering (SCE)",
  "School of Chemical Engineering (SCHEME)",
  "School of Computer Science and Engineering (SCOPE)",
  "School of Computer Science Engineering and Information Systems (SCORE)",
  "School of Electrical Engineering (SELECT)",
  "School of Electronics Engineering (SENSE)",
  "School of Healthcare Science and Engineering (SHINE)",
  "School of Mechanical Engineering (SMEC)",
  "School of Social Sciences and Languages (SSL)",
  "School of Hotel & Tourism Management (HOT)",
  "VIT School of Agricultural Innovations And Advanced Learning (VAIAL)",
  "VIT Business School (VIT BS)",
  "VIT School of Design (V-SIGN)",
  "VIT School of Media, Arts and Technology (V-SMART)",
  "School of Architecture (V-SPARC)",
];

export const mhBlocks = Array.from({ length: 20 }, (_, i) => `MH-${String.fromCharCode(65 + i)}`).filter(
  (block) => !["MH-I", "MH-O"].includes(block)
);

export const lhBlocks = Array.from({ length: 10 }, (_, i) => `LH-${String.fromCharCode(65 + i)}`).filter(
  (block) => block !== "LH-I"
);

lhBlocks.push("RJT", "E-Annex", "B-Annex", "G-Annex");

export const allHostelBlocks = [...mhBlocks, ...lhBlocks, "Day Boarder"];
